-- 1. Persona (base) — todos los duplicados de ese documento
SELECT
    ddr.ID_FORMULARIO,
    ddr.TP_PERSONA,
    ddr.NM_NOMBRE,
    ddr.NM_APELLIDO,
    ddr.TP_DOCUMENTO,
    ddr.NU_DOCUMENTO,
    ddr.NU_DOCUMENTO_STR,
    ddr.NU_CUIL_CUIT,
    ddr.NU_CUIL_CUIT_STR,
    ddr.CD_NACIONALIDAD,
    ddr.NM_RAZON_SOCIAL,
    ddr.TP_SOCIETARIO,
    ddr.CD_ESTADO_CIVIL,
    ddr.CD_NUPCIAS,
    ddr.CD_SEXO,
    ddr.DT_NACIMIENTO,
    ddr.DS_CALLE,
    ddr.DS_NUMERO,
    ddr.DS_CALLE_ENTRE,
    ddr.NU_PISO,
    ddr.NU_DEPARTAMENTO,
    ddr.CD_BARRIO,
    ddr.DS_LOTE,
    ddr.DS_MANZANA,
    ddr.CD_PROVINCIA,
    ddr.CD_DEPARTAMENTO,
    ddr.CD_LOCALIDAD,
    ddr.DS_DETALLES,
    ddr.NM_NOMBRE_CONYUGUE,
    ddr.NM_APELLIDO_CONYUGUE,
    ddr.CD_DOCUMENTO_CONYUGUE,
    ddr.NU_DOCUMENTO_CONYUGUE,
    ddr.DT_CASAMIENTO,
    ddr.CD_LIBRO,
    ddr.CD_ACTA,
    ddr.DS_EMAIL,
    ddr.PREFIJO_CEL,
    ddr.NU_CELULAR,
    ddr.PREFIJO_TEL,
    ddr.NU_TELEFONO,
    ddr.IN_BAJA_LOGICA,
    ddr.ID_PERSONA_RGDB1,
    ddr.MIG_ID_PERSONA,
    ddr.MIG_DT_UPD,
    ddr.CD_USER_STORE,
    ddr.DT_STORE,
    ddr.CD_USER_LAST_UPDATE,
    ddr.DT_LAST_UPDATE
FROM DIG_DOC_R62 ddr
WHERE ddr.TP_PERSONA = 'PF'
  AND ddr.NU_DOCUMENTO = :p_nu_documento
ORDER BY ddr.DT_LAST_UPDATE DESC NULLS LAST;

-- 2. Titulares activos (B2) + inmueble — seguro, porque B2→inmueble es "muchos a uno"
SELECT
    ddrb.ID_MATRICULA, ddrb.NU_SEQUENCE, ddrb.CD_PERSONA,
    ddrb.NU_NUMERADOR, ddrb.NU_DENOMINADOR, ddrb.CD_SITUACION,
    ddrb.DT_DESDE, ddrb.TM_DESDE, ddrb.CD_COLUM_2, ddrb.NU_ASIEN_2,
    ddrb.NU_CASO_ORIGEN, ddrb.CD_CALIFICACION_ADICI002, ddrb.CD_CALIFICACION,
    ddrb.CD_ESTA_2, ddrb.DS_PORCENTAJE, ddrb.DT_ALTA, ddrb.DT_MODIFICACION,
    ddrb.CD_USER_STORE AS CD_USER_STORE_ACT, ddrb.CD_USER_UPDATE,
    ddrb.ELIMINADO, ddrb.RECIENTE, ddrb.MIG_FHPI_ID, ddrb.MIG_DT_UPD AS MIG_DT_UPD_ACT,
    ddrb.MIG_DT_CREACION_PROC AS MIG_DT_CREACION_PROC_ACT, ddrb.FIDU, ddrb.FORMACION,
    ddrb.DS_OBSERVA AS DS_OBSERVA_ACT,
    -- inmueble
    ddr0.NU_MATRICULA, ddr0.DT_CREACION, ddr0.DS_PROCEDENCIA, ddr0.CD_ESTADO,
    ddr0.DS_INMUEBLE, ddr0.A0_DS_UBICACION, ddr0.A0_SUP_TITULO, ddr0.A0_SUP_PLANO,
    ddr0.A0_NU_SUPERFICIE, ddr0.A0_DS_LIMITES, ddr0.A0_DS_DESIGNACION,
    ddr0.A0_CD_DEPARTAMENTO, ddr0.A0_CD_DISTRITO, ddr0.NU_TOMO, ddr0.NU_FOJA,
    ddr0.CD_TOMO, ddr0.NU_INSCRIPCION, ddr0.CD_DISTRITO, ddr0.CD_DEPARTAMENTO,
    ddr0.CD_CLAS_INMU, ddr0.CD_CATEG_ESTADO
FROM DIG_DOC_R00_B2 ddrb
LEFT JOIN DIG_DOC_R00 ddr0 ON ddr0.ID_MATRICULA = ddrb.ID_MATRICULA
WHERE ddrb.CD_PERSONA IN (
    SELECT ID_FORMULARIO FROM DIG_DOC_R62
    WHERE TP_PERSONA = 'PF' AND NU_DOCUMENTO = :p_nu_documento
)
ORDER BY ddrb.CD_PERSONA, ddrb.ID_MATRICULA;

-- 3. Titulares históricos (B4) + inmueble
SELECT
    ddrb2.CD_PERSONA_H, ddrb2.ID_MATRICULA, ddrb2.NU_NUMERAD_2, ddrb2.NU_DENOMINAD_2,
    ddrb2.CD_SITUACI_2, ddrb2.DT_HASTA, ddrb2.TM_HASTA, ddrb2.CD_COLUM_2, ddrb2.NU_ASIEN_2,
    ddrb2.DT_DES_2, ddrb2.TM_DES_2, ddrb2.CD_CALIFICACI_2, ddrb2.CD_CALIFICACION_ADICI004,
    ddrb2.NU_CASO_ORIG_2, ddrb2.DS_PORCENTA_2, ddrb2.MIG_FHPI_ID, ddrb2.MIG_DT_UPD,
    ddrb2.MIG_DT_CREACION_PROC, ddrb2.DS_OBSERVA,
    -- inmueble
    ddr0.NU_MATRICULA, ddr0.DS_INMUEBLE, ddr0.CD_ESTADO, ddr0.DS_PROCEDENCIA
FROM DIG_DOC_R00_B4 ddrb2
LEFT JOIN DIG_DOC_R00 ddr0 ON ddr0.ID_MATRICULA = ddrb2.ID_MATRICULA
WHERE ddrb2.CD_PERSONA_H IN (
    SELECT ID_FORMULARIO FROM DIG_DOC_R62
    WHERE TP_PERSONA = 'PF' AND NU_DOCUMENTO = :p_nu_documento
)
ORDER BY ddrb2.CD_PERSONA_H, ddrb2.ID_MATRICULA;

-- 4. DIG_DOC_R00_B5 no vigentes + inmueble
SELECT
    ddrb3.CD_PERSONA_P, ddrb3.ID_MATRICULA, ddrb3.NU_NUMERAD_2, ddrb3.NU_DENOMINAD_2,
    ddrb3.CD_SITUACI_2, ddrb3.DT_DES_2, ddrb3.TM_DES_2, ddrb3.CD_COLUM_2, ddrb3.NU_ASIEN_2,
    ddrb3.NU_CASO_ORIG_2, ddrb3.CD_CALIFICACI_2, ddrb3.CD_CALIFICACION_ADICI005,
    ddrb3.DT_HAS_2, ddrb3.CD_ESTA_2, ddrb3.DS_PORCENTA_2, ddrb3.DT_ALTA, ddrb3.DT_MODIFICACION,
    ddrb3.CD_USER_STORE, ddrb3.CD_USER_UPDATE, ddrb3.ELIMINADO, ddrb3.RECIENTE, ddrb3.FIDU,
    ddrb3.FORMACION, ddrb3.MIG_FHPI_ID, ddrb3.MIG_DT_UPD, ddrb3.MIG_DT_CREACION_PROC,
    ddrb3.DS_OBSERVA, ddrb3.TIPO_TITU,
    -- inmueble
    ddr0.NU_MATRICULA, ddr0.DS_INMUEBLE, ddr0.CD_ESTADO, ddr0.DS_PROCEDENCIA
FROM DIG_DOC_R00_B5 ddrb3
LEFT JOIN DIG_DOC_R00 ddr0 ON ddr0.ID_MATRICULA = ddrb3.ID_MATRICULA
WHERE ddrb3.CD_PERSONA_P IN (
    SELECT ID_FORMULARIO FROM DIG_DOC_R62
    WHERE TP_PERSONA = 'PF' AND NU_DOCUMENTO = :p_nu_documento
)
ORDER BY ddrb3.CD_PERSONA_P, ddrb3.ID_MATRICULA;