-- ¿El ID_MATRICULA huérfano de B2 es en realidad otra clave de DIG_DOC_R00?
-- Complementa titularidad_huerfana_cruces.sql (24/09/2026). Se prueba contra
-- NU_MATRICULA, ID_MAT_RGDB1, MIG_INM_ID_INMUEBLE e ID_INMUEBLE, y si en esa
-- matrícula candidata la MISMA persona (o su documento) ya es titular vivo.

-- Bloque 1: densidad de R00 por rango de ID (¿los IDs bajos existen?).
SELECT FLOOR(ID_MATRICULA/1000000) AS MILLON, COUNT(*) AS FILAS_R00,
       MIN(ID_MATRICULA) AS MIN_ID, MAX(ID_MATRICULA) AS MAX_ID
FROM DIG_DOC_R00 GROUP BY FLOOR(ID_MATRICULA/1000000) ORDER BY 1;

-- Bloque 2: por ID huérfano, en qué clave alternativa aparece y si la persona
-- es titular viva ahí.
WITH H AS (
    SELECT DISTINCT b.ID_MATRICULA, b.CD_PERSONA, p.NU_DOCUMENTO
    FROM DIG_DOC_R00_B2 b
    JOIN DIG_DOC_R62 p ON p.ID_FORMULARIO = b.CD_PERSONA AND p.TP_PERSONA = 'PF'
    WHERE NVL(b.ELIMINADO,0) = 0
      AND NOT EXISTS (SELECT 1 FROM DIG_DOC_R00 i WHERE i.ID_MATRICULA = b.ID_MATRICULA)
)
SELECT h.ID_MATRICULA, h.CD_PERSONA, h.NU_DOCUMENTO,
       (SELECT COUNT(*) FROM DIG_DOC_R00 i WHERE i.NU_MATRICULA = h.ID_MATRICULA) AS EN_NU_MATRICULA,
       (SELECT COUNT(*) FROM DIG_DOC_R00 i WHERE i.ID_MAT_RGDB1 = h.ID_MATRICULA) AS EN_ID_MAT_RGDB1,
       (SELECT COUNT(*) FROM DIG_DOC_R00 i WHERE i.MIG_INM_ID_INMUEBLE = h.ID_MATRICULA) AS EN_MIG_INM_ID,
       (SELECT COUNT(*) FROM DIG_DOC_R00 i WHERE i.ID_INMUEBLE = h.ID_MATRICULA) AS EN_ID_INMUEBLE,
       (SELECT COUNT(*) FROM DIG_DOC_R00 i JOIN DIG_DOC_R00_B2 x ON x.ID_MATRICULA = i.ID_MATRICULA
          JOIN DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
         WHERE NVL(x.ELIMINADO,0) = 0 AND q.NU_DOCUMENTO = h.NU_DOCUMENTO
           AND (i.NU_MATRICULA = h.ID_MATRICULA OR i.ID_MAT_RGDB1 = h.ID_MATRICULA
                OR i.MIG_INM_ID_INMUEBLE = h.ID_MATRICULA OR i.ID_INMUEBLE = h.ID_MATRICULA)) AS DOC_TITULAR_EN_CANDIDATA,
       (SELECT MIN(i.ID_MATRICULA) FROM DIG_DOC_R00 i
         WHERE i.NU_MATRICULA = h.ID_MATRICULA OR i.ID_MAT_RGDB1 = h.ID_MATRICULA
            OR i.MIG_INM_ID_INMUEBLE = h.ID_MATRICULA OR i.ID_INMUEBLE = h.ID_MATRICULA) AS ID_CANDIDATA
FROM H
ORDER BY h.ID_MATRICULA, h.CD_PERSONA;
