-- Validación de titulares huérfanos (25/09/2026) — paso 2 (CLAVE_EQUIVOCADA)
-- ampliado.
--
-- NU_MATRICULA tiene formato <departamento><número de 8 dígitos>
-- (ej. 400586391 = depto 4, número 586391). Se prueban dos hipótesis de
-- "clave equivocada" sobre el ID_MATRICULA huérfano:
--   K  el ID es el NU_MATRICULA completo de una matrícula real
--   S  el ID es el número SIN el prefijo de departamento
--      (MOD(NU_MATRICULA, 100000000) = ID)
--   R  el ID es el NU_MATRICULA_PRO (procedencia) de un formulario de
--      matriculación R18 -> candidata = R18.CD_MATRICULA (la matrícula que el
--      trámite generó). Se enlaza por número (R18_A1) o por el caso de la fila
--      (DOCUMENTO_ANEXO). Cubre las numeraciones nuevas con desplazamiento
--      (ej. 510088819) que la hipótesis S no ve.
--   T  el ID es de una matrícula de la migración (V_PROCEDENCIA_DOMNIO_MIG) cuya
--      cabecera R00 ya no existe -> candidata = matrícula real con el mismo
--      tomo / foja / inscripción / departamento.
-- Para cada candidato se mide si el MISMO documento / la MISMA persona figura
-- como titular ahí (B2 vivo o B4 histórico). Una coincidencia de número sin
-- coincidencia de titular no prueba nada: hay hasta ~18 departamentos con el
-- mismo número.
--
-- Una fila por (registro huérfano, matrícula candidata). Solo lectura. Export:
--   RunQuery ../queries/validacion_huerfanos_04_clave_alternativa.sql --csv ../out/validacion_huerfanos_04_clave_alternativa_<fecha>

WITH O AS (
    SELECT b.ID_MATRICULA, b.NU_SEQUENCE, b.CD_PERSONA, b.DT_ALTA, b.DT_DESDE, b.NU_CASO_ORIGEN,
           CASE WHEN p.NU_DOCUMENTO IS NULL OR REGEXP_LIKE(p.NU_DOCUMENTO,'^0+$')
                  OR p.NU_DOCUMENTO IN ('99907804','1') THEN NULL
                ELSE p.NU_DOCUMENTO END AS DOC_OK
    FROM SIRCLAN.DIG_DOC_R00_B2 b
    JOIN SIRCLAN.DIG_DOC_R62 p ON p.ID_FORMULARIO = b.CD_PERSONA AND p.TP_PERSONA = 'PF'
    WHERE NVL(b.ELIMINADO,0) = 0
      AND NOT EXISTS (SELECT 1 FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = b.ID_MATRICULA)
),
M AS (
    SELECT ID_MATRICULA, NU_MATRICULA, CD_ESTADO, CD_DEPARTAMENTO, DT_STORE, CD_USER_STORE,
           NU_TOMO, NU_FOJA, NU_INSCRIPCION,
           MOD(NU_MATRICULA, 100000000) AS NUM_SIN_DEPTO
    FROM SIRCLAN.DIG_DOC_R00
),
R18C AS (
    SELECT DISTINCT O.ID_MATRICULA, O.NU_SEQUENCE, r.CD_MATRICULA
    FROM O JOIN SIRCLAN.DIG_DOC_R18_A1 a1 ON TRIM(a1.NU_MATRICULA_PRO) = TO_CHAR(O.ID_MATRICULA)
           JOIN SIRCLAN.DIG_DOC_R18 r ON r.NU_FORMULARIO = a1.NU_FORMULARIO
    UNION
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, r.CD_MATRICULA
    FROM O JOIN SIRCLAN.DOCUMENTO_ANEXO a ON a.TP_ANEXO = 'R18' AND a.DOCUMENT_KEY = O.NU_CASO_ORIGEN
           JOIN SIRCLAN.DIG_DOC_R18 r ON r.NU_FORMULARIO = TO_NUMBER(REGEXP_SUBSTR(a.ID_ANEXO, '[0-9]+'))
),
CAND AS (
    SELECT O.*, 'K' AS HIPOTESIS, M.ID_MATRICULA AS ID_CAND, M.NU_MATRICULA AS NU_CAND, M.CD_ESTADO, M.CD_DEPARTAMENTO,
           M.DT_STORE AS R00_DT_STORE, M.CD_USER_STORE AS R00_USER
      FROM O JOIN M ON M.NU_MATRICULA = O.ID_MATRICULA
    UNION ALL
    SELECT O.*, 'S', M.ID_MATRICULA, M.NU_MATRICULA, M.CD_ESTADO, M.CD_DEPARTAMENTO, M.DT_STORE, M.CD_USER_STORE
      FROM O JOIN M ON M.NUM_SIN_DEPTO = O.ID_MATRICULA AND M.NU_MATRICULA <> O.ID_MATRICULA
    UNION ALL
    SELECT O.*, 'R', M.ID_MATRICULA, M.NU_MATRICULA, M.CD_ESTADO, M.CD_DEPARTAMENTO, M.DT_STORE, M.CD_USER_STORE
      FROM O JOIN R18C c ON c.ID_MATRICULA = O.ID_MATRICULA AND c.NU_SEQUENCE = O.NU_SEQUENCE
             JOIN M ON M.ID_MATRICULA = c.CD_MATRICULA
    UNION ALL
    SELECT O.*, 'T', M.ID_MATRICULA, M.NU_MATRICULA, M.CD_ESTADO, M.CD_DEPARTAMENTO, M.DT_STORE, M.CD_USER_STORE
      FROM O JOIN SIRCLAN.V_PROCEDENCIA_DOMNIO_MIG v ON v.ID_MATRICULA = O.ID_MATRICULA
             JOIN M ON M.NU_TOMO = v.NU_TOMO AND M.NU_FOJA = v.NU_FOJA AND M.NU_INSCRIPCION = v.NU_INSCRIPCION
                   AND M.CD_DEPARTAMENTO = v.CD_DEPARTAMENTO AND M.ID_MATRICULA <> O.ID_MATRICULA
)
SELECT
    C.ID_MATRICULA || '-' || C.NU_SEQUENCE AS ID_REGISTRO,
    C.ID_MATRICULA, C.NU_SEQUENCE, C.CD_PERSONA, C.DOC_OK AS NU_DOCUMENTO,
    C.HIPOTESIS, C.ID_CAND, C.NU_CAND, C.CD_ESTADO AS CAND_CD_ESTADO, C.CD_DEPARTAMENTO AS CAND_DEPTO,
    TO_CHAR(C.R00_DT_STORE, 'YYYY-MM-DD') AS CAND_R00_DT_STORE, C.R00_USER AS CAND_R00_USER,
    COUNT(*) OVER (PARTITION BY C.ID_MATRICULA, C.NU_SEQUENCE, C.HIPOTESIS) AS N_CANDIDATOS_HIPOTESIS,
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B2 x WHERE x.ID_MATRICULA = C.ID_CAND AND NVL(x.ELIMINADO,0) = 0) AS CAND_TIT_ACTIVOS,
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B2 x
      WHERE x.ID_MATRICULA = C.ID_CAND AND NVL(x.ELIMINADO,0) = 0 AND x.CD_PERSONA = C.CD_PERSONA) AS PERS_TIT_B2,
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B2 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
      WHERE x.ID_MATRICULA = C.ID_CAND AND NVL(x.ELIMINADO,0) = 0 AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_TIT_B2,
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B4 x WHERE x.ID_MATRICULA = C.ID_CAND AND x.CD_PERSONA_H = C.CD_PERSONA) AS PERS_TIT_B4,
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B4 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA_H
      WHERE x.ID_MATRICULA = C.ID_CAND AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_TIT_B4,
    (SELECT TO_CHAR(MAX(x.DT_HASTA), 'YYYY-MM-DD') FROM SIRCLAN.DIG_DOC_R00_B4 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA_H
      WHERE x.ID_MATRICULA = C.ID_CAND AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_B4_MAX_DT_HASTA,
    (SELECT MAX(x.NU_CASO_ORIG_2) FROM SIRCLAN.DIG_DOC_R00_B4 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA_H
      WHERE x.ID_MATRICULA = C.ID_CAND AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_B4_CASO,
    (SELECT TO_CHAR(MIN(x.DT_ALTA), 'YYYY-MM-DD HH24:MI:SS') FROM SIRCLAN.DIG_DOC_R00_B2 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
      WHERE x.ID_MATRICULA = C.ID_CAND AND NVL(x.ELIMINADO,0) = 0 AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_B2_MIN_DT_ALTA,
    (SELECT MAX(x.NU_CASO_ORIGEN) FROM SIRCLAN.DIG_DOC_R00_B2 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
      WHERE x.ID_MATRICULA = C.ID_CAND AND NVL(x.ELIMINADO,0) = 0 AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_B2_CASO,
    -- Nombre del titular con el mismo documento en la candidata (para no dar
    -- por buena una coincidencia de DNI con otra persona)
    (SELECT MIN(TRIM(q.NM_APELLIDO) || ', ' || TRIM(q.NM_NOMBRE)) FROM SIRCLAN.DIG_DOC_R00_B2 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
      WHERE x.ID_MATRICULA = C.ID_CAND AND NVL(x.ELIMINADO,0) = 0 AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_B2_NOMBRE,
    (SELECT MIN(TRIM(q.NM_APELLIDO) || ', ' || TRIM(q.NM_NOMBRE)) FROM SIRCLAN.DIG_DOC_R00_B4 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA_H
      WHERE x.ID_MATRICULA = C.ID_CAND AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_B4_NOMBRE,
    (SELECT MIN(x.DS_PORCENTA_2) FROM SIRCLAN.DIG_DOC_R00_B4 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA_H
      WHERE x.ID_MATRICULA = C.ID_CAND AND q.NU_DOCUMENTO = C.DOC_OK) AS DOC_B4_PORCENTAJE,
    -- ¿El mismo caso dejó asientos R14 en la matrícula candidata?
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R14 r WHERE r.ID_MATRICULA = C.ID_CAND AND r.NU_CASO = C.NU_CASO_ORIGEN) AS CASO_ASIENTOS_EN_CAND,
    -- Asientos R14 de la candidata creados el mismo día que la fila huérfana
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R14 r WHERE r.ID_MATRICULA = C.ID_CAND
        AND TRUNC(r.DT_STORE) = TRUNC(C.DT_ALTA)) AS ASIENTOS_CAND_MISMO_DIA
FROM CAND C
ORDER BY C.ID_MATRICULA, C.NU_SEQUENCE, C.HIPOTESIS, C.ID_CAND
