-- Validación de titulares huérfanos (25/09/2026) — pasos 2, 6, 7 y 8.
-- Una fila por ID_MATRICULA huérfano (IDs con al menos un titular PF vivo en
-- B2 y sin fila en DIG_DOC_R00). Mide qué quedó de esa "matrícula" en el resto
-- del sistema, para distinguir:
--   * cabecera R00 borrada con el resto del formulario vivo (hijas A*/B*),
--   * ID que nunca tuvo formulario (solo B2),
--   * ID heredado de la migración 2017 (snapshot DIG_DOC_R00_B2_20170902,
--     V_PROCEDENCIA_DOMNIO_MIG, TOMOS_MAL_CREADOS),
--   * ID que en realidad es un NU_MATRICULA (clave equivocada).
-- Nada de esto prueba por sí solo que el titular sobre: son indicios.
--
-- Bloque 1: una fila por ID.  Bloque 2: densidad de R00 por banda de ID.
-- Solo lectura. Export:
--   RunQuery ../queries/validacion_huerfanos_03_trazas_id.sql --csv ../out/validacion_huerfanos_03_trazas_id_<fecha>

WITH IDS AS (
    SELECT b.ID_MATRICULA AS ID, COUNT(*) AS FILAS_PF_VIVAS,
           MIN(b.DT_ALTA) AS MIN_ALTA, MAX(b.DT_ALTA) AS MAX_ALTA
    FROM SIRCLAN.DIG_DOC_R00_B2 b
    JOIN SIRCLAN.DIG_DOC_R62 p ON p.ID_FORMULARIO = b.CD_PERSONA AND p.TP_PERSONA = 'PF'
    WHERE NVL(b.ELIMINADO,0) = 0
      AND NOT EXISTS (SELECT 1 FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = b.ID_MATRICULA)
    GROUP BY b.ID_MATRICULA
),
T AS (
    SELECT IDS.*,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B2 x WHERE x.ID_MATRICULA = IDS.ID) AS B2_FILAS_TOTAL,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B2 x WHERE x.ID_MATRICULA = IDS.ID AND NVL(x.ELIMINADO,0) = 1) AS B2_FILAS_ELIMINADO,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B2 x JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
          WHERE x.ID_MATRICULA = IDS.ID AND q.TP_PERSONA = 'PJ') AS B2_FILAS_PJ,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B4 x WHERE x.ID_MATRICULA = IDS.ID) AS B4_FILAS,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B5 x WHERE x.ID_MATRICULA = IDS.ID) AS B5_FILAS,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_A1 x WHERE x.ID_MATRICULA = IDS.ID) AS A1_FILAS,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_A2 x WHERE x.ID_MATRICULA = IDS.ID) AS A2_FILAS,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B1 x WHERE x.ID_MATRICULA = IDS.ID) AS B1_FILAS,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B3 x WHERE x.ID_MATRICULA = IDS.ID) AS B3_FILAS,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B8 x WHERE x.ID_MATRICULA = IDS.ID) AS B8_FILAS,
        (SELECT MIN(x.TP_PROCEDENCIA || '/' || x.CD_NOTA_DOMINIO || '/' || x.NU_MATRICU_2 || '/T' || x.NU_TOMO || '-F' || x.NU_FOJA || '-I' || x.NU_INSCRIPCION)
           FROM SIRCLAN.DIG_DOC_R00_B1 x WHERE x.ID_MATRICULA = IDS.ID) AS B1_PROCEDENCIA,
        (SELECT MIN(x.NU_MATRICU_2) FROM SIRCLAN.DIG_DOC_R00_B1 x WHERE x.ID_MATRICULA = IDS.ID) AS B1_NU_MATRICULA_ORIGEN,
        (SELECT MIN(x.DS_NOMENCLA) FROM SIRCLAN.DIG_DOC_R00_B3 x WHERE x.ID_MATRICULA = IDS.ID) AS B3_NOMENCLA,
        (SELECT MIN(x.NRO_PADRON) FROM SIRCLAN.DIG_DOC_R00_B8 x WHERE x.ID_MATRICULA = IDS.ID) AS B8_PADRON,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R14 x WHERE x.ID_MATRICULA = IDS.ID) AS R14_ASIENTOS,
        (SELECT MIN(x.NU_CASO) FROM SIRCLAN.DIG_DOC_R14 x WHERE x.ID_MATRICULA = IDS.ID) AS R14_MIN_CASO,
        (SELECT TO_CHAR(MIN(x.DT_CREACION), 'YYYY-MM-DD') FROM SIRCLAN.DIG_DOC_R14 x WHERE x.ID_MATRICULA = IDS.ID) AS R14_MIN_DT,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R20 x WHERE x.ID_MATRICULA = IDS.ID) AS R20_FILAS,
        (SELECT MIN(x.NU_MATRICULA) FROM SIRCLAN.DIG_DOC_R20 x WHERE x.ID_MATRICULA = IDS.ID) AS R20_NU_MATRICULA,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B2_20170902 x WHERE x.ID_MATRICULA = IDS.ID) AS B2_SNAPSHOT_2017,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00_B4_20170902 x WHERE x.ID_MATRICULA = IDS.ID) AS B4_SNAPSHOT_2017,
        (SELECT COUNT(*) FROM SIRCLAN.V_PROCEDENCIA_DOMNIO_MIG x WHERE x.ID_MATRICULA = IDS.ID) AS PROC_MIG_FILAS,
        (SELECT MIN(x.NU_MAT_ACT) FROM SIRCLAN.V_PROCEDENCIA_DOMNIO_MIG x WHERE x.ID_MATRICULA = IDS.ID) AS PROC_MIG_NU_MAT_ACT,
        (SELECT MIN(x.NU_MAT_ORI) FROM SIRCLAN.V_PROCEDENCIA_DOMNIO_MIG x WHERE x.ID_MATRICULA = IDS.ID) AS PROC_MIG_NU_MAT_ORI,
        (SELECT MIN(x.ID_INMUELBLE_EN_RGDB1) FROM SIRCLAN.V_PROCEDENCIA_DOMNIO_MIG x WHERE x.ID_MATRICULA = IDS.ID) AS PROC_MIG_ID_INM_RGDB1,
        (SELECT COUNT(*) FROM SIRCLAN.V_PROCEDENCIA_DOMNIO_MIG x WHERE x.ID_INMUELBLE_EN_RGDB1 = IDS.ID) AS ES_ID_INMUEBLE_RGDB1,
        (SELECT COUNT(*) FROM SIRCLAN.TOMOS_MAL_CREADOS x WHERE x.ID_MATR_TOMO = IDS.ID OR x.ID_MATR_SIRC = IDS.ID) AS TOMOS_MAL_CREADOS,
        (SELECT COUNT(*) FROM SIRCWEB.DIG_DOC_R00 x WHERE x.ID_MATRICULA = IDS.ID) AS SIRCWEB_R00,
        (SELECT COUNT(*) FROM SIRCWEB.DIG_DOC_R00_B2 x WHERE x.ID_MATRICULA = IDS.ID) AS SIRCWEB_B2,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.NU_MATRICULA = IDS.ID) AS ES_NU_MATRICULA,
        (SELECT MIN(i.ID_MATRICULA) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.NU_MATRICULA = IDS.ID) AS ID_REAL_POR_NU,
        (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MAT_RGDB1 = IDS.ID OR i.MIG_INM_ID_INMUEBLE = IDS.ID OR i.ID_INMUEBLE = IDS.ID) AS EN_OTRA_CLAVE_R00,
        (SELECT MAX(i.ID_MATRICULA) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA < IDS.ID) AS R00_ID_ANTERIOR,
        (SELECT MIN(i.ID_MATRICULA) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA > IDS.ID) AS R00_ID_SIGUIENTE
    FROM IDS
),
GEM AS (
    SELECT h.ID_MATRICULA AS ID, COUNT(DISTINCT y.ID_MATRICULA) AS N_GEMELAS_NOMENC, MIN(y.ID_MATRICULA) AS ID_GEMELA_NOMENC
    FROM SIRCLAN.DIG_DOC_R00_B3 h
    JOIN SIRCLAN.DIG_DOC_R00_B3 y ON y.DS_NOMENCLA = h.DS_NOMENCLA AND y.ID_MATRICULA <> h.ID_MATRICULA
    JOIN SIRCLAN.DIG_DOC_R00 r ON r.ID_MATRICULA = y.ID_MATRICULA
    WHERE h.ID_MATRICULA IN (SELECT ID FROM IDS)
      AND h.DS_NOMENCLA IS NOT NULL AND NOT REGEXP_LIKE(TRIM(h.DS_NOMENCLA), '^0*$')
    GROUP BY h.ID_MATRICULA
)
SELECT
    T.ID AS ID_MATRICULA,
    CASE WHEN T.ID <= 253249 THEN 'A' WHEN T.ID < 1400001 THEN 'B' WHEN T.ID <= 1736177 THEN 'C'
         WHEN T.ID < 5000000 THEN 'D' WHEN T.ID <= 6396110 THEN 'E' ELSE 'F' END AS BANDA,
    T.FILAS_PF_VIVAS, TO_CHAR(T.MIN_ALTA, 'YYYY-MM-DD HH24:MI:SS') AS MIN_DT_ALTA_B2,
    TO_CHAR(T.MAX_ALTA, 'YYYY-MM-DD HH24:MI:SS') AS MAX_DT_ALTA_B2,
    T.B2_FILAS_TOTAL, T.B2_FILAS_ELIMINADO, T.B2_FILAS_PJ, T.B4_FILAS, T.B5_FILAS,
    T.A1_FILAS, T.A2_FILAS, T.B1_FILAS, T.B3_FILAS, T.B8_FILAS,
    T.B1_PROCEDENCIA, T.B1_NU_MATRICULA_ORIGEN,
    (SELECT MIN(i.ID_MATRICULA) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.NU_MATRICULA = T.B1_NU_MATRICULA_ORIGEN) AS ID_MATRICULA_ORIGEN_REAL,
    T.B3_NOMENCLA, T.B8_PADRON, G.N_GEMELAS_NOMENC, G.ID_GEMELA_NOMENC,
    T.R14_ASIENTOS, T.R14_MIN_CASO, T.R14_MIN_DT, T.R20_FILAS, T.R20_NU_MATRICULA,
    T.B2_SNAPSHOT_2017, T.B4_SNAPSHOT_2017,
    T.PROC_MIG_FILAS, T.PROC_MIG_NU_MAT_ACT, T.PROC_MIG_NU_MAT_ORI, T.PROC_MIG_ID_INM_RGDB1, T.ES_ID_INMUEBLE_RGDB1,
    T.TOMOS_MAL_CREADOS, T.SIRCWEB_R00, T.SIRCWEB_B2,
    T.ES_NU_MATRICULA, T.ID_REAL_POR_NU, T.EN_OTRA_CLAVE_R00,
    T.R00_ID_ANTERIOR,
    (SELECT TO_CHAR(i.DT_STORE, 'YYYY-MM-DD') FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = T.R00_ID_ANTERIOR) AS R00_ANT_DT_STORE,
    (SELECT i.CD_USER_STORE FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = T.R00_ID_ANTERIOR) AS R00_ANT_USER,
    T.R00_ID_SIGUIENTE,
    (SELECT TO_CHAR(i.DT_STORE, 'YYYY-MM-DD') FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = T.R00_ID_SIGUIENTE) AS R00_SIG_DT_STORE,
    (SELECT i.CD_USER_STORE FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = T.R00_ID_SIGUIENTE) AS R00_SIG_USER
FROM T LEFT JOIN GEM G ON G.ID = T.ID
ORDER BY T.ID;

-- Bloque 2: densidad de DIG_DOC_R00 y de las tablas de titularidad por banda de
-- ID, para ver si la banda es un rango "vivo" del sistema o uno ajeno.
WITH R AS (
    SELECT CASE WHEN ID_MATRICULA <= 253249 THEN 'A' WHEN ID_MATRICULA < 1400001 THEN 'B' WHEN ID_MATRICULA <= 1736177 THEN 'C'
                WHEN ID_MATRICULA < 5000000 THEN 'D' WHEN ID_MATRICULA <= 6396110 THEN 'E' ELSE 'F' END AS BANDA,
           ID_MATRICULA, DT_STORE, CD_USER_STORE, NU_MATRICULA
    FROM SIRCLAN.DIG_DOC_R00
)
SELECT BANDA, COUNT(*) AS R00_FILAS, MIN(ID_MATRICULA) AS MIN_ID, MAX(ID_MATRICULA) AS MAX_ID,
       TO_CHAR(MIN(DT_STORE), 'YYYY-MM-DD') AS MIN_DT_STORE, TO_CHAR(MAX(DT_STORE), 'YYYY-MM-DD') AS MAX_DT_STORE,
       SUM(CASE WHEN CD_USER_STORE IN ('MIGRACION','RPI_RV_MIG') OR CD_USER_STORE IS NULL THEN 1 ELSE 0 END) AS R00_MIGRACION,
       SUM(CASE WHEN NU_MATRICULA IS NULL THEN 1 ELSE 0 END) AS R00_SIN_NU_MATRICULA
FROM R GROUP BY BANDA ORDER BY BANDA;

-- Bloque 3: todas las filas de B2 (cualquier TP_PERSONA, vivas o no) y de B4 que
-- apuntan a un ID inexistente, por banda: ¿las PF vivas son un subconjunto de un
-- fenómeno más grande?
WITH X AS (
    SELECT 'B2' AS TABLA, b.ID_MATRICULA, NVL(b.ELIMINADO,0) AS ELIM, b.DT_ALTA, b.CD_USER_STORE
      FROM SIRCLAN.DIG_DOC_R00_B2 b WHERE NOT EXISTS (SELECT 1 FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = b.ID_MATRICULA)
    UNION ALL
    SELECT 'B4', h.ID_MATRICULA, 0, CAST(NULL AS TIMESTAMP), CAST(NULL AS VARCHAR2(30))
      FROM SIRCLAN.DIG_DOC_R00_B4 h WHERE NOT EXISTS (SELECT 1 FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = h.ID_MATRICULA)
    UNION ALL
    SELECT 'B2_2017', s.ID_MATRICULA, NVL(s.ELIMINADO,0), s.DT_ALTA, s.CD_USER_STORE
      FROM SIRCLAN.DIG_DOC_R00_B2_20170902 s WHERE NOT EXISTS (SELECT 1 FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = s.ID_MATRICULA)
)
SELECT TABLA,
       CASE WHEN ID_MATRICULA <= 253249 THEN 'A' WHEN ID_MATRICULA < 1400001 THEN 'B' WHEN ID_MATRICULA <= 1736177 THEN 'C'
            WHEN ID_MATRICULA < 5000000 THEN 'D' WHEN ID_MATRICULA <= 6396110 THEN 'E' ELSE 'F' END AS BANDA,
       COUNT(*) AS FILAS, COUNT(DISTINCT ID_MATRICULA) AS IDS, SUM(ELIM) AS ELIMINADAS,
       TO_CHAR(MIN(DT_ALTA), 'YYYY-MM-DD') AS MIN_ALTA, TO_CHAR(MAX(DT_ALTA), 'YYYY-MM-DD') AS MAX_ALTA
FROM X GROUP BY TABLA,
       CASE WHEN ID_MATRICULA <= 253249 THEN 'A' WHEN ID_MATRICULA < 1400001 THEN 'B' WHEN ID_MATRICULA <= 1736177 THEN 'C'
            WHEN ID_MATRICULA < 5000000 THEN 'D' WHEN ID_MATRICULA <= 6396110 THEN 'E' ELSE 'F' END
ORDER BY 1, 2
