-- Validación de titulares huérfanos (25/09/2026) — paso 2 a 5 del pedido.
-- Una fila por (registro huérfano, registro de B2 VIVO en matrícula EXISTENTE
-- relacionado, tipo de vínculo). Sirve para comparar lado a lado huérfano vs.
-- registro real y decidir si el huérfano es copia, borrador o historia propia.
--
-- Tipos de vínculo (TIPO_VINCULO):
--   P  misma persona (CD_PERSONA)
--   D  mismo documento, OTRO CD_PERSONA (indicio, no identidad)
--   C  mismo NU_CASO_ORIGEN (cualquier persona)
--   K  "clave equivocada": el ID huérfano es el NU_MATRICULA de la matrícula
--      real -> todos sus titulares vivos
--   N  matrícula "gemela" por nomenclatura catastral (DIG_DOC_R00_B3.DS_NOMENCLA
--      del ID huérfano = la de una matrícula real; se excluye el placeholder '0')
--   G  matrícula gemela por padrón (DIG_DOC_R00_B8.NRO_PADRON)
--   R  matrícula real tocada por un asiento R14 del mismo caso de origen
--
-- Solo lectura. Export:
--   RunQuery ../queries/validacion_huerfanos_02_relacionados.sql --csv ../out/validacion_huerfanos_02_relacionados_<fecha>

WITH O AS (
    SELECT b.ID_MATRICULA, b.NU_SEQUENCE, b.CD_PERSONA, b.NU_CASO_ORIGEN,
           CASE WHEN p.NU_DOCUMENTO IS NULL OR REGEXP_LIKE(p.NU_DOCUMENTO,'^0+$')
                  OR p.NU_DOCUMENTO IN ('99907804','1') THEN NULL
                ELSE p.NU_DOCUMENTO END AS DOC_OK
    FROM SIRCLAN.DIG_DOC_R00_B2 b
    JOIN SIRCLAN.DIG_DOC_R62 p ON p.ID_FORMULARIO = b.CD_PERSONA AND p.TP_PERSONA = 'PF'
    WHERE NVL(b.ELIMINADO,0) = 0
      AND NOT EXISTS (SELECT 1 FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = b.ID_MATRICULA)
),
VIVOS AS (
    SELECT x.ID_MATRICULA, x.NU_SEQUENCE, x.CD_PERSONA, x.NU_CASO_ORIGEN, q.NU_DOCUMENTO
    FROM SIRCLAN.DIG_DOC_R00_B2 x
    JOIN SIRCLAN.DIG_DOC_R00 i ON i.ID_MATRICULA = x.ID_MATRICULA
    LEFT JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
    WHERE NVL(x.ELIMINADO,0) = 0
),
IDS AS (SELECT DISTINCT ID_MATRICULA AS ID FROM O),
GEMELA_N AS (
    SELECT DISTINCT IDS.ID, y.ID_MATRICULA AS ID_REAL
    FROM IDS
    JOIN SIRCLAN.DIG_DOC_R00_B3 h ON h.ID_MATRICULA = IDS.ID
    JOIN SIRCLAN.DIG_DOC_R00_B3 y ON y.DS_NOMENCLA = h.DS_NOMENCLA AND y.ID_MATRICULA <> IDS.ID
    JOIN SIRCLAN.DIG_DOC_R00 r ON r.ID_MATRICULA = y.ID_MATRICULA
    WHERE h.DS_NOMENCLA IS NOT NULL AND NOT REGEXP_LIKE(TRIM(h.DS_NOMENCLA), '^0*$')
),
GEMELA_G AS (
    SELECT DISTINCT IDS.ID, y.ID_MATRICULA AS ID_REAL
    FROM IDS
    JOIN SIRCLAN.DIG_DOC_R00_B8 h ON h.ID_MATRICULA = IDS.ID
    JOIN SIRCLAN.DIG_DOC_R00_B8 y ON y.NRO_PADRON = h.NRO_PADRON AND NVL(y.DS_PADRON,-1) = NVL(h.DS_PADRON,-1)
                                 AND y.ID_MATRICULA <> IDS.ID
    JOIN SIRCLAN.DIG_DOC_R00 r ON r.ID_MATRICULA = y.ID_MATRICULA
    WHERE h.NRO_PADRON IS NOT NULL AND NOT REGEXP_LIKE(TRIM(h.NRO_PADRON), '^0*$')
),
CASO_MAT AS (
    SELECT DISTINCT r.NU_CASO, r.ID_MATRICULA AS ID_REAL
    FROM SIRCLAN.DIG_DOC_R14 r JOIN SIRCLAN.DIG_DOC_R00 i ON i.ID_MATRICULA = r.ID_MATRICULA
    WHERE r.NU_CASO IN (SELECT NU_CASO_ORIGEN FROM O WHERE NU_CASO_ORIGEN IS NOT NULL)
),
PARES AS (
    SELECT O.ID_MATRICULA AS H_ID, O.NU_SEQUENCE AS H_SEQ, 'P' AS TIPO, v.ID_MATRICULA AS R_ID, v.NU_SEQUENCE AS R_SEQ
      FROM O JOIN VIVOS v ON v.CD_PERSONA = O.CD_PERSONA
    UNION ALL
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'D', v.ID_MATRICULA, v.NU_SEQUENCE
      FROM O JOIN VIVOS v ON v.NU_DOCUMENTO = O.DOC_OK AND v.CD_PERSONA <> O.CD_PERSONA
    UNION ALL
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'C', v.ID_MATRICULA, v.NU_SEQUENCE
      FROM O JOIN VIVOS v ON v.NU_CASO_ORIGEN = O.NU_CASO_ORIGEN
    UNION ALL
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'K', v.ID_MATRICULA, v.NU_SEQUENCE
      FROM O JOIN SIRCLAN.DIG_DOC_R00 r ON r.NU_MATRICULA = O.ID_MATRICULA
             JOIN VIVOS v ON v.ID_MATRICULA = r.ID_MATRICULA
    UNION ALL
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'N', v.ID_MATRICULA, v.NU_SEQUENCE
      FROM O JOIN GEMELA_N g ON g.ID = O.ID_MATRICULA JOIN VIVOS v ON v.ID_MATRICULA = g.ID_REAL
    UNION ALL
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'G', v.ID_MATRICULA, v.NU_SEQUENCE
      FROM O JOIN GEMELA_G g ON g.ID = O.ID_MATRICULA JOIN VIVOS v ON v.ID_MATRICULA = g.ID_REAL
    UNION ALL
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'R', v.ID_MATRICULA, v.NU_SEQUENCE
      FROM O JOIN CASO_MAT c ON c.NU_CASO = O.NU_CASO_ORIGEN JOIN VIVOS v ON v.ID_MATRICULA = c.ID_REAL
)
SELECT
    PA.TIPO AS TIPO_VINCULO,
    PA.H_ID || '-' || PA.H_SEQ AS ID_REGISTRO_HUERFANO,
    PA.R_ID || '-' || PA.R_SEQ AS ID_REGISTRO_RELACIONADO,
    r.NU_MATRICULA AS R_NU_MATRICULA, r.CD_ESTADO AS R_CD_ESTADO,
    TO_CHAR(r.DT_CREACION, 'YYYY-MM-DD') AS R_DT_CREACION,
    TO_CHAR(r.DT_STORE, 'YYYY-MM-DD HH24:MI:SS') AS R_DT_STORE_R00,
    r.CD_USER_STORE AS R_USER_STORE_R00,
    x.ID_MATRICULA AS R_ID_MATRICULA, x.NU_SEQUENCE AS R_NU_SEQUENCE, x.CD_PERSONA AS R_CD_PERSONA,
    q.NU_DOCUMENTO AS R_NU_DOCUMENTO,
    TRIM(q.NM_APELLIDO) || ', ' || TRIM(q.NM_NOMBRE) AS R_NOMBRE_COMPLETO,
    x.NU_CASO_ORIGEN AS R_NU_CASO_ORIGEN, x.CD_USER_STORE AS R_CD_USER_STORE,
    TO_CHAR(x.DT_ALTA, 'YYYY-MM-DD HH24:MI:SS') AS R_DT_ALTA,
    TO_CHAR(x.DT_DESDE, 'YYYY-MM-DD') AS R_DT_DESDE,
    TO_CHAR(x.TM_DESDE, 'YYYY-MM-DD HH24:MI:SS') AS R_TM_DESDE,
    x.CD_SITUACION AS R_CD_SITUACION, x.RECIENTE AS R_RECIENTE,
    x.NU_NUMERADOR AS R_NU_NUMERADOR, x.NU_DENOMINADOR AS R_NU_DENOMINADOR,
    x.DS_PORCENTAJE AS R_DS_PORCENTAJE, x.CD_COLUM_2 AS R_CD_COLUM_2, x.NU_ASIEN_2 AS R_NU_ASIEN_2,
    x.MIG_FHPI_ID AS R_MIG_FHPI_ID
FROM PARES PA
JOIN SIRCLAN.DIG_DOC_R00_B2 x ON x.ID_MATRICULA = PA.R_ID AND x.NU_SEQUENCE = PA.R_SEQ
JOIN SIRCLAN.DIG_DOC_R00 r ON r.ID_MATRICULA = x.ID_MATRICULA
LEFT JOIN SIRCLAN.DIG_DOC_R62 q ON q.ID_FORMULARIO = x.CD_PERSONA
ORDER BY PA.H_ID, PA.H_SEQ, PA.TIPO, x.ID_MATRICULA, x.NU_SEQUENCE
