-- Validación de titulares huérfanos (25/09/2026) — paso 8 (origen del problema).
--
-- Hipótesis de mecanismo a verificar: el trámite "Generación de Mat SIRC"
-- (procesos BPM 1230/4029/4033/4035, formulario R18) crea la matrícula nueva
-- R18.CD_MATRICULA a partir de una procedencia R18_A1 (CD_NOTA_DOM_PRO='MAT',
-- NU_MATRICULA_PRO = número de la matrícula de origen SIN departamento,
-- R18.CD_DEPARTAMENTO_PROV aparte). Si los titulares se grabaron en B2 con
-- ID_MATRICULA = NU_MATRICULA_PRO en lugar de CD_MATRICULA, queda exactamente
-- una fila huérfana cuyo ID es un "número de matrícula sin departamento".
--
-- Dos vías de enlace, una fila por (registro huérfano, formulario R18):
--   CASO   el R18 está anexado (DOCUMENTO_ANEXO) al caso NU_CASO_ORIGEN de la fila
--   NUMERO algún R18 tiene NU_MATRICULA_PRO = ID huérfano (cualquier caso); se
--          informa la distancia en días entre el R18 y la fila B2
-- Correlación no es causalidad: que el R18 exista y coincida hace plausible el
-- mecanismo, pero la confirmación es funcional (equipo SIRCLAN).
--
-- Solo lectura. Export:
--   RunQuery ../queries/validacion_huerfanos_05_r18_matriculacion.sql --csv ../out/validacion_huerfanos_05_r18_matriculacion_<fecha>

WITH O AS (
    SELECT b.ID_MATRICULA, b.NU_SEQUENCE, b.CD_PERSONA, b.NU_CASO_ORIGEN, b.DT_ALTA
    FROM SIRCLAN.DIG_DOC_R00_B2 b
    JOIN SIRCLAN.DIG_DOC_R62 p ON p.ID_FORMULARIO = b.CD_PERSONA AND p.TP_PERSONA = 'PF'
    WHERE NVL(b.ELIMINADO,0) = 0
      AND NOT EXISTS (SELECT 1 FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = b.ID_MATRICULA)
),
ANX AS (
    SELECT a.DOCUMENT_KEY, TO_NUMBER(REGEXP_SUBSTR(a.ID_ANEXO, '[0-9]+')) AS NU_FORMULARIO
    FROM SIRCLAN.DOCUMENTO_ANEXO a
    WHERE a.TP_ANEXO = 'R18'
      AND a.DOCUMENT_KEY IN (SELECT NU_CASO_ORIGEN FROM O WHERE NU_CASO_ORIGEN IS NOT NULL)
),
R18P AS (
    SELECT r.NU_FORMULARIO, r.CD_MATRICULA, r.NU_ID_MATRICULA_ENTRADA, r.CD_DEPARTAMENTO_PROV,
           r.CD_ESTADO_MATRICULA, r.CD_USUARIO, r.DT_STORE,
           a1.CD_NOTA_DOM_PRO, a1.NU_MATRICULA_PRO, a1.TP_PROCEDENCIA,
           a1.NU_TOMO_PRO, a1.NU_INSCRIPCION_PRO, a1.QT_FOJAS_PRO
    FROM SIRCLAN.DIG_DOC_R18 r
    LEFT JOIN SIRCLAN.DIG_DOC_R18_A1 a1 ON a1.NU_FORMULARIO = r.NU_FORMULARIO
),
PARES AS (
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'CASO' AS VIA, x.NU_FORMULARIO
      FROM O JOIN ANX x ON x.DOCUMENT_KEY = O.NU_CASO_ORIGEN
    UNION
    SELECT O.ID_MATRICULA, O.NU_SEQUENCE, 'NUMERO', a1.NU_FORMULARIO
      FROM O JOIN SIRCLAN.DIG_DOC_R18_A1 a1 ON TRIM(a1.NU_MATRICULA_PRO) = TO_CHAR(O.ID_MATRICULA)
)
SELECT
    PA.ID_MATRICULA || '-' || PA.NU_SEQUENCE AS ID_REGISTRO,
    PA.ID_MATRICULA, PA.NU_SEQUENCE, PA.VIA, R.NU_FORMULARIO AS R18_NU_FORMULARIO,
    R.CD_MATRICULA AS R18_CD_MATRICULA,
    (SELECT COUNT(*) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = R.CD_MATRICULA) AS R18_MATRICULA_EXISTE,
    (SELECT MIN(i.NU_MATRICULA) FROM SIRCLAN.DIG_DOC_R00 i WHERE i.ID_MATRICULA = R.CD_MATRICULA) AS R18_NU_MATRICULA_NUEVA,
    R.NU_ID_MATRICULA_ENTRADA AS R18_ID_MAT_ENTRADA, R.CD_DEPARTAMENTO_PROV AS R18_DEPTO_PROV,
    R.CD_ESTADO_MATRICULA AS R18_ESTADO, R.CD_USUARIO AS R18_USUARIO,
    TO_CHAR(R.DT_STORE, 'YYYY-MM-DD HH24:MI:SS') AS R18_DT_STORE,
    R.CD_NOTA_DOM_PRO, R.NU_MATRICULA_PRO, R.TP_PROCEDENCIA, R.NU_TOMO_PRO, R.NU_INSCRIPCION_PRO, R.QT_FOJAS_PRO,
    CASE WHEN TRIM(R.NU_MATRICULA_PRO) = TO_CHAR(PA.ID_MATRICULA) THEN 1 ELSE 0 END AS PRO_IGUAL_ID_HUERFANO,
    (SELECT MIN(i.ID_MATRICULA) FROM SIRCLAN.DIG_DOC_R00 i
      WHERE i.NU_MATRICULA = CASE WHEN REGEXP_LIKE(TRIM(R.NU_MATRICULA_PRO), '^[0-9]+$')
                                       AND REGEXP_LIKE(TRIM(R.CD_DEPARTAMENTO_PROV), '^[0-9]+$')
                                  THEN TO_NUMBER(TRIM(R.CD_DEPARTAMENTO_PROV)) * 100000000 + TO_NUMBER(TRIM(R.NU_MATRICULA_PRO)) END
    ) AS ID_MATRICULA_PROCEDENCIA,
    ROUND(CAST(O.DT_ALTA AS DATE) - CAST(R.DT_STORE AS DATE), 3) AS DIAS_R18_A_FILA_B2
FROM PARES PA
JOIN O ON O.ID_MATRICULA = PA.ID_MATRICULA AND O.NU_SEQUENCE = PA.NU_SEQUENCE
JOIN R18P R ON R.NU_FORMULARIO = PA.NU_FORMULARIO
ORDER BY PA.ID_MATRICULA, PA.NU_SEQUENCE, PA.VIA, R.NU_FORMULARIO
